name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0
      
      - name: Set up JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Up MySQL container
        run: docker-compose up -d db-cpa
      
      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dspring.profiles.active=docker -Dmaven.test.failure.ignore=false test
        
      - name: Down Mysql for tests
        run: docker-compose down mysql_db
      
      - name: Check pattern
        run: mvn checkstyle:checkstyle
        
  build-and-deploy-artifact:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.4.0
      
    - name: DockerHub login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: |
          cpaApplication/cpa-back:1.0.0
          cpaApplication/cpa-back:latest
